version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000 - reload
    volumes:
      - ./app:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./mapmyworld.db